<script setup lang="ts">
import { computed } from "vue";
import { DayType, DayTypeDescriptions } from "@/model/day-types";
import { type ScheduleDay } from "@/model/schedule-sheet";
import { isMonday, isWeekend } from "date-fns";
import { fontColorFromBackground } from "@/utils/color";

const { scheduleDay } = defineProps<{
	scheduleDay: ScheduleDay;
	// selection: [],
	// error_groups: ErrorGroup[],
}>();

const classes = computed(() => {
	//We can't use purely type_string because that conflicts with
	//classes generated by vuetify based on theme colors
	return [
		"t-" + typeString.value,
		{
			// "has-warning": this.error_groups.some(x => !x.fatal),
			// "has-error": this.error_groups.some(x => x.fatal),
			// "selected": this.is_selected,
			weekend: isWeekend(scheduleDay.date) /* || isHoliday(scheduleDay.date) */,
			monday: isMonday(scheduleDay.date),
			// "first": this.selection[0] == this.day,
			// "last": this.selection[this.selection.length - 1] == this.day,
		},
	];
});

const typeString = computed(() => {
	return Object.entries(DayType)[scheduleDay.type][1] as string;
});

const style = computed(() => {
	const color = DayTypeDescriptions[scheduleDay.type].color;
	return { backgroundColor: color, color: fontColorFromBackground(color) };
});

// is_selected(): boolean {
// 	return this.selection.includes(this.day);
// },
</script>

<template>
	<td :class="classes" :style="style">
		<template v-if="scheduleDay.type === DayType.shift">
			{{ scheduleDay.shiftStart }}
			<br />
			{{ scheduleDay.shiftEnd }}
		</template>
		<template v-else>
			{{ DayTypeDescriptions[scheduleDay.type].label }}
		</template>
	</td>
</template>

<style scoped>
td:hover {
	/* background-color: #ddd; */
	filter: brightness(90%);
	cursor: pointer;
}
td {
	border: 0.5px solid #ccc;
	text-align: center;
	min-width: 2.7em;
	width: 100vw;
	height: 3.75em;
	text-shadow: white 0px 0px 20px;
	font-weight: 500;
	font-size: 15px;
	letter-spacing: 1px;
}
.selected {
	border-top-color: var(--v-selected-border-base);
	border-bottom-color: var(--v-selected-border-base);
	background-color: #ccc;
	text-align: center;
	filter: brightness(85%);
}
.last.selected {
	border-right-color: var(--v-selected-border-base);
}
.first.selected {
	border-left-color: var(--v-selected-border-base);
}
.has-warning {
	box-shadow: inset 0px -4px var(--v-warning-base);
}
.has-error {
	box-shadow: inset 0px -4px var(--v-error-base);
}
.monday {
	border-left: 2px solid #555;
	min-width: calc(2.7em + 4px);
}
.monday.first.selected {
	border-left: 2px solid #555;
}
.weekend {
	filter: hue-rotate(-20deg);
	z-index: -1;
}
.weekend:hover {
	filter: brightness(90%) !important;
}
.weekend.t-empty,
.weekend.t-shift {
	filter: brightness(95%);
	z-index: -1;
}
.weekend.t-empty.selected,
.weekend.t-shift.selected {
	filter: brightness(80%);
}
</style>
